# version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: gis_postgres
    environment:
      POSTGRES_DB: gis_db
      POSTGRES_USER: gis_user
      POSTGRES_PASSWORD: gis_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gis_user -d gis_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: